### ISSUE TITLE
Why the need of providing "components" when decoding

### ISSUE THREAD

**Issue by Ridote** [MrVallentin/LoadBMP#5]
With components I mean the last parameter (LOADBMP_RGBA/LOADBMP_RGB)

Isn't this something you could actually get from

**bmp_info_header[14];**

You could even leave the components parameter but make it a reference so whoever calls the function can get the value of the component back, instead of providing it, so you can read random bmps without having to worry about their bits per pixels

**Comment by vallentin** [comment]
Yes, that would be something you'd be able to infer from the header. However, LoadBMP does not support reading BMPs with an alpha channel. If that was needed, I always resorted to using PNGs.

So when you specify `LOADBMP_RGBA`, then it's just adding an alpha channel of `255`. Whereas with `LOADBMP_RGB` then no alpha channel would be allocated. It's basically just to make it easier on the develop, if they know they'll need an alpha channel. Say, if you have a magenta background representing transparent.

But yes, I agree, it would be nice to be able to query the components as well.

**Comment by Ridote** [comment]
Ahh, thanks for the quick reply! I guess that make sense and answers the question, I'm still looking in the code just out of curiosity. 

Very thank you and nice work!
